# Generated by Django 6.0.1 on 2026-01-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('business', 'Business'), ('academic', 'Academic')], default='technology', max_length=20),
        ),
    ]
